services:
  db:
    container_name: dbase
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_USER: ${USR}
      POSTGRES_DB: ${DB}
    ports:
      - "3432:5432"
    volumes:
      - 1702data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USR}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  web:
    container_name: appl
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - HOST_PROJECT_PATH=${PROJECT_PATH}
    volumes:
      - ./uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - app-network

volumes:
  1702data:

networks:
  app-network: