services:
  db:
    container_name: dbase
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1702
      POSTGRES_DB: 1702school
    ports:
      - "3432:5432"
    volumes:
      - 1702data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - app-network

  web:
    container_name: wsgiapp
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:admin1702@db:5432/1702school
      HOST_PROJECT_PATH: ${PROJECT_PATH} 
    volumes:
      - ./uploads:/uploads
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - app-network

volumes:
  1702data:

networks:
  app-network: