"""init

Revision ID: ee6f208e42d1
Revises: 
Create Date: 2026-07-07 07:40:32.509853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6f208e42d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('hidden_test_cases', sa.JSON(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('task_name')
    )
    op.create_table('usrs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('user_role', sa.Enum('ADMIN', 'STUDENT', 'TEACHER', 'BANNED', name='usertype'), nullable=False),
    sa.Column('reg_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('REVIEWED', 'PENDING', 'OK', 'COMPILATION_ERROR', 'RUNTIME_ERROR', 'TIME_LIMIT', 'WALL_TIME_LIMIT', 'MEMORY_LIMIT', 'WRONG_ANSWER', 'PRESENTATION_ERROR', 'CHECK_FAILED', 'PARTIAL_SOLUTION', 'SECURITY_VIOLATION', 'PENDING_CHECK', 'PENDING_REVIEW', 'ACCEPTED_TESTING', 'IGNORED', 'DISQUALIFIED', 'REJECTED', 'SUMMONED_DEFENCE', 'STYLE_VIOLATION', 'NO_CHANGE', 'REJUDGE', 'FULL_REJUDGE', name='submissionstatus'), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usrs.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('submission_review',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['usrs.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_review')
    op.drop_table('submissions')
    op.drop_table('usrs')
    op.drop_table('tasks')
    # ### end Alembic commands ###
